// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function readRequiredSupabaseEnv(name: string, placeholders: string[]) {
  const value = process.env[name];
  const isPlaceholder = placeholders.some((placeholder) => value?.includes(placeholder));

  if (!value || isPlaceholder) {
    const message = `Missing Supabase environment variable(s): ${name}. Set your real Supabase URL and service role key.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return value;
}

function createSupabaseAdminClient() {
  const supabaseUrl = readRequiredSupabaseEnv("SUPABASE_URL", ["your-project.supabase.co"]);
  const serviceRoleKey = readRequiredSupabaseEnv("SUPABASE_SERVICE_ROLE_KEY", [
    "your-service-role-key",
    "your-publishable-key",
  ]);

  if (
    serviceRoleKey === process.env.SUPABASE_PUBLISHABLE_KEY ||
    serviceRoleKey.startsWith("sb_publishable_")
  ) {
    const message =
      "SUPABASE_SERVICE_ROLE_KEY must be the secret service_role key, not the publishable/anon key.";
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(supabaseUrl, serviceRoleKey, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

type SupabaseAdminClient = ReturnType<typeof createSupabaseAdminClient>;

let _supabaseAdmin: SupabaseAdminClient | undefined;

function getSupabaseAdmin() {
  _supabaseAdmin ??= createSupabaseAdminClient();
  return _supabaseAdmin;
}

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Load inside server handlers: const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
// Top-level import is safe only in other .server.ts modules - route files and *.functions.ts ship to the client bundle.
export const supabaseAdmin = new Proxy({} as SupabaseAdminClient, {
  get(_, prop: keyof SupabaseAdminClient) {
    return getSupabaseAdmin()[prop];
  },
});
